#!/bin/bash

timestamp=$(date +%s)
tmpbranch="tmp"$timestamp

# check github
if [[ -z `git config --get remote.bigai-ai.url` ]]; then
        git remote add bigai-ai https://github.com/pringwong/civrealm.git
fi
git pull bigai-ai

# push to github
git checkout dev
git checkout -b $tmpbranch
if git apply --check .github.patch; then
        git apply .github.patch
        git add .
        git commit -m "compatible with github"
        git checkout bigai-ai/dev
        git merge -Xours $tmpbranch
        git add .
        git commit -m "to github"
        git push bigai-ai HEAD:dev
fi

# delete tmp branch
git branch -D $tmpbranch
git checkout dev

