#!/bin/bash
readarray -t link_array < <(jq --compact-output '.[]' .github.link)

function replace_url(){
        for item in "${link_array[@]}"; do
                gitlab_name=$(jq --raw-output '.gitlab' <<< "$item")
                github_name=$(jq --raw-output '.github' <<< "$item")
                if [ `grep -c "$gitlab_name" $1` -ne '0' ]; then
                        sed -i "s#$gitlab_name#$github_name#g" $1
                        echo "Replaced file $1 containing $gitlab_name"
                fi
        done
}
function recur(){
        files=`ls $1`
        for file in $files
        do
                dir=$1/$file
                if test -d $dir
                then
                        if grep -q "docs" <<< "$dir"; then
                                recur $dir
                        fi
                else
                        replace_url $dir
                fi
        done
}

timestamp=$(date +%s)
tmpbranch="tmp"$timestamp

# check github
if [[ -z `git config --get remote.bigai-ai.url` ]]; then
        git remote add bigai-ai git@github.com:bigai-ai/civrealm.git
fi
git pull bigai-ai

# push to github
git checkout dev
if git apply --check .github.patch; then
        # create tmp branch
        git checkout -b $tmpbranch
        # apply patch
        git apply .github.patch
        # replace url
        recur .
        # commit changes
        git add .
        git commit -m "compatible with github"
        # merge to github
        git checkout bigai-ai/dev
        git merge -Xtheirs $tmpbranch
        # push to github
        git add .
        git commit -m "to github"
        git push bigai-ai HEAD:dev
        # delete tmp branch
        git branch -D $tmpbranch
fi
git checkout dev
