site_name: CivRealm Documentation
repo_url: https://github.com/bigai-ai/civrealm
repo_name: civilization/civrealm
copyright: Copyright &copy; 2023 BIGAI
site_dir: public

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - content.code.copy
    - content.code.select
    - content.tabs.link
  logo: assets/logo-h48.png
  favicon: assets/logo-64.png
  palette:
    scheme: bigai
  icon:
    repo: fontawesome/brands/gitlab
    annotation: material/arrow-right-circle

extra_css:
  - css/extra.css

plugins:
  - search
  - autorefs
  - table-reader
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src/civrealm]
          options:
            show_root_heading: true
            show_source: true
            show_root_full_path: true
            docstring_style: numpy
            heading_level: 3

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

nav:
  - Home: index.md
  - Getting Started:
      - Install and Setup:
          - Requirements: getting_started/requirements.md
          - Installation: getting_started/installation.md
      - Quick Start:
          - Basic Usage: getting_started/basic_usage.md
          - Your First Agent: getting_started/first_agent.md
          - Visualization: getting_started/visualization.md
      - Trouble Shooting: getting_started/trouble_shooting.md
  - Advanced Materials:
      - Game:
          - Game Settings: advanced_materials/game_settings.md
          - Full-Game:
              - Usage: advanced_materials/fullgame_usage.md
              - General Description: advanced_materials/fullgame_description.md
              - Observation Details: advanced_materials/fullgame_observation.md
              - Action Details: advanced_materials/fullgame_action.md
          - Mini-Game:
              - Usage: advanced_materials/minigame_usage.md
              - Setting: advanced_materials/minigame_setting.md
              - Create Minigame: advanced_materials/minigame_create.md
      - Agent:
          - Tensor Agent: advanced_materials/tensor_agent.md
          - LLM Agent: advanced_materials/llm_agent.md
      - Train Scheme:
          - Parallel Training: advanced_materials/parallel_training.md
      - Architecture: advanced_materials/architecture.md
  - API Reference:
      - Environments: api_reference/environments.md
      - Wrappers: api_reference/wrappers.md
      - Observations: api_reference/observations.md
  - Releases: releases/releases.md
  - Notes:
      - Contribute To CivRealm: notes/contribute.md
      - Performance Benchmarks: notes/benchmarks.md
  - Misc:
      - FAQ: misc/faq.md
      - Resources: misc/resources.md

use_directory_urls: false
