#!/bin/bash

# the path of shared store space, like ~/mas/
data_path=$1
docker_image=$2
minitasks_path=$data_path/minitasks/

for dir in `ls $minitasks_path`
do
    if [[ "$dir" == minitask* ]]; then
        for file in `ls $minitasks_path$dir/`
        do
            echo $file
            docker cp $minitasks_path$dir/$file $docker_image:/var/lib/tomcat10/webapps/data/savegames/$dir/
        done
    fi
done
